apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: order
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: orderflow
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: orderflow
        tier: backend
    spec:
      containers:
      - name: backend
        image: runtesting/order-backend:1.3
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: orders
        - name: DB_USERNAME
          value: orderuser
        - name: DB_PASSWORD
          value: orderpass
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: CORS_ALLOW_ALL_ORIGINS
          value: "true"