apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: orderflow-frontend
  namespace: orderflow
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`orderflow.local`)
      kind: Rule
      services:
        - name: frontend
          port: 80

